# Data Preprocessing

### Workflow
- Import Required Libraries
- Load Dataset
- Separate Features and Target Variable
- Combine Train and Test Dataset
- Handle Missing Values
- Handle Outliers
- Feature Engineering
- Encode Categorical Features
- Feature Scaling
- Split Train and Test Dataset
- Save Processed Dataset

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
pd.set_option()

In [3]:
train_df = pd.read_csv("../dataset/raw/train.csv")
test_df = pd.read_csv("../dataset/raw/test.csv")

In [4]:
train_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
test_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [6]:
# separate Features and target
X = train_df.drop("SalePrice",axis=1)
y = train_df['SalePrice']

In [7]:
# Combine train, test data for data preprocessing
df = pd.concat([X,test_df], axis=0 , ignore_index=True)

In [19]:
df.sample(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
2570,2571,20,RL,NaN,17871,Pave,NaN,IR2,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2007,WD,Normal
2642,2643,160,RM,24.0,2760,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2006,WD,Normal
1355,1356,80,RL,102.0,10192,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,GdPrv,NaN,0,9,2006,WD,Normal
909,910,60,RL,149.0,12589,Pave,NaN,IR2,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2009,WD,Normal
2256,2257,60,RL,60.0,7500,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal

In [18]:
df.shape

(2919, 80)

In [23]:
df.dtypes.value_counts()

object     43
int64      26
float64    11
Name: count, dtype: int64

## Handle Missing Values

In [13]:
missing_cols = df.isna().sum()
missing_cols = missing_cols[missing_cols>0]

In [14]:
missing_cols

MSZoning           4
LotFrontage      486
Alley           2721
Utilities          2
Exterior1st        1
Exterior2nd        1
MasVnrType      1766
MasVnrArea        23
BsmtQual          81
BsmtCond          82
BsmtExposure      82
BsmtFinType1      79
BsmtFinSF1         1
BsmtFinType2      80
BsmtFinSF2         1
BsmtUnfSF          1
TotalBsmtSF        1
Electrical         1
BsmtFullBath       2
BsmtHalfBath       2
KitchenQual        1
Functional         2
FireplaceQu     1420
GarageType       157
GarageYrBlt      159
GarageFinish     159
GarageCars         1
GarageArea         1
GarageQual       159
GarageCond       159
PoolQC          2909
Fence           2348
MiscFeature     2814
SaleType           1
dtype: int64

In [15]:
missing_cols.dtypes

dtype('int64')

In [34]:
# percentages 
missing_cols_p = df.isna().sum()/len(df) 
missing_cols_p = missing_cols_p[missing_cols_p>0]
missing_cols_p

MSZoning        0.001370
LotFrontage     0.166495
Alley           0.932169
Utilities       0.000685
Exterior1st     0.000343
Exterior2nd     0.000343
MasVnrType      0.605002
MasVnrArea      0.007879
BsmtQual        0.027749
BsmtCond        0.028092
BsmtExposure    0.028092
BsmtFinType1    0.027064
BsmtFinSF1      0.000343
BsmtFinType2    0.027407
BsmtFinSF2      0.000343
BsmtUnfSF       0.000343
TotalBsmtSF     0.000343
Electrical      0.000343
BsmtFullBath    0.000685
BsmtHalfBath    0.000685
KitchenQual     0.000343
Functional      0.000685
FireplaceQu     0.486468
GarageType      0.053786
GarageYrBlt     0.054471
GarageFinish    0.054471
GarageCars      0.000343
GarageArea      0.000343
GarageQual      0.054471
GarageCond      0.054471
PoolQC          0.996574
Fence           0.804385
MiscFeature     0.964029
SaleType        0.000343
dtype: float64

In [35]:
missing_cols_p[missing_cols_p < 0.01]

MSZoning        0.001370
Utilities       0.000685
Exterior1st     0.000343
Exterior2nd     0.000343
MasVnrArea      0.007879
BsmtFinSF1      0.000343
BsmtFinSF2      0.000343
BsmtUnfSF       0.000343
TotalBsmtSF     0.000343
Electrical      0.000343
BsmtFullBath    0.000685
BsmtHalfBath    0.000685
KitchenQual     0.000343
Functional      0.000685
GarageCars      0.000343
GarageArea      0.000343
SaleType        0.000343
dtype: float64

In [39]:
# separate numeric and categorical columns 
missing = df.isna().sum()
missing = missing[missing > 0]
missing_cols = missing.index

num_missing_cols = df[missing_cols].select_dtypes(include='number').columns.tolist()
cat_missing_cols = df[missing_cols].select_dtypes(include='object').columns.tolist()

In [40]:
num_missing_cols

['LotFrontage',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 'BsmtFullBath',
 'BsmtHalfBath',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea']

In [41]:
cat_missing_cols

['MSZoning',
 'Alley',
 'Utilities',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType']

In [43]:
df[cat_missing_cols].T

,0,1,2,3,4,5,6,7,8,9,...,2909,2910,2911,2912,2913,2914,2915,2916,2917,2918
MSZoning,RL,RL,RL,RL,RL,RL,RL,RL,RM,RL,...,RM,RM,RL,RM,RM,RM,RM,RL,RL,RL
Alley,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Utilities,AllPub,AllPub,AllPub,AllPub,AllPub,AllPub,AllPub,AllPub,AllPub,AllPub,...,AllPub,AllPub,AllPub,AllPub,AllPub,AllPub,AllPub,AllPub,AllPub,AllPub
Exterior1st,VinylSd,MetalSd,VinylSd,Wd Sdng,VinylSd,VinylSd,VinylSd,HdBoard,BrkFace,MetalSd,...,CemntBd,CemntBd,Plywood,CemntBd,CemntBd,CemntBd,CemntBd,VinylSd,HdBoard,HdBoard
Exterior2nd,VinylSd,MetalSd,VinylSd,Wd Shng,VinylSd,VinylSd,VinylSd,HdBoard,Wd Shng,MetalSd,...,CmentBd,CmentBd,Plywood,CmentBd,CmentBd,CmentBd,CmentBd,VinylSd,Wd Shng,HdBoard
MasVnrType,BrkFace,NaN,BrkFace,NaN,BrkFace,NaN,Stone,Stone,NaN,NaN,...,NaN,NaN,BrkFace,NaN,NaN,NaN,NaN,NaN,NaN,BrkFace
BsmtQual,Gd,Gd,Gd,TA,Gd,Gd,Ex,Gd,TA,TA,...,Gd,TA,TA,TA,TA,TA,TA,TA,Gd,Gd
BsmtCond,TA,TA,TA,Gd,TA,TA,TA,TA,TA,TA,...,TA,TA,TA,TA,TA,TA,TA,TA,TA,TA
BsmtExposure,No,Gd,Mn,No,Av,No,Av,Mn,No,No,...,Av,No,Av,No,No,No,No,No,Av,Av
BsmtFinType1,GLQ,ALQ,GLQ,ALQ,GLQ,GLQ,GLQ,ALQ,Unf,GLQ,...,GLQ,Rec,Rec,Rec,Unf,Unf,Rec,ALQ,GLQ,LwQ
BsmtFinType2,Unf,Unf,Unf,Unf,Unf,Unf,Unf,BLQ,Unf,Unf,...,Unf,Unf,BLQ,Unf,Unf,Unf,Unf,Unf,Unf,Unf
Electrical,SBrkr,SBrkr,SBrkr,SBrkr,SBrkr,SBrkr,SBrkr,SBrkr,FuseF,SBrkr,...,SBrkr,SBrkr,SBrkr,SBrkr,SBrkr,SBrkr,SBrkr,SBrkr,SBrkr,SBrkr
KitchenQual,Gd,TA,Gd,Gd,Gd,TA,Gd,TA,TA,TA,...,TA,TA,TA,TA,TA,TA,TA,TA,TA,TA
Functional,Typ,Typ,Typ,Typ,Typ,Typ,Typ,Typ,Min1,Typ,...,Typ,Typ,Typ,Typ,Typ,Typ,Typ,Typ,Typ,Typ
FireplaceQu,NaN,TA,TA,Gd,TA,NaN,Gd,TA,TA,TA,...,NaN,NaN,TA,NaN,NaN,NaN,NaN,TA,NaN,TA
GarageType,Attchd,Attchd,Attchd,Detchd,Attchd,Attchd,Attchd,Attchd,Detchd,Attchd,...,NaN,Attchd,Attchd,CarPort,NaN,NaN,CarPort,Detchd,NaN,Attchd
GarageFinish,RFn,RFn,RFn,Unf,RFn,Unf,RFn,RFn,Unf,RFn,...,NaN,Unf,RFn,Unf,NaN,NaN,Unf,Unf,NaN,Fin
GarageQual,TA,TA,TA,TA,TA,TA,TA,TA,Fa,Gd,...,NaN,TA,TA,TA,NaN,NaN,TA,TA,NaN,TA
GarageCond,TA,TA,TA,TA,TA,TA,TA,TA,TA,TA,...,NaN,Fa,TA,TA,NaN,NaN,TA,TA,NaN,TA
PoolQC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fence,NaN,NaN,NaN,NaN,NaN,MnPrv,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,GdPrv,NaN,NaN,NaN,MnPrv,NaN
MiscFeature,NaN,NaN,NaN,NaN,NaN,Shed,NaN,Shed,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Shed,NaN
SaleType,WD,WD,WD,WD,WD,WD,WD,WD,WD,WD,...,WD,WD,WD,WD,WD,WD,WD,WD,WD,WD

In [45]:
df[num_missing_cols]

,LotFrontage,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,BsmtFullBath,BsmtHalfBath,GarageYrBlt,GarageCars,GarageArea
0,65.0,196.0,706.0,0.0,150.0,856.0,1.0,0.0,2003.0,2.0,548.0
1,80.0,0.0,978.0,0.0,284.0,1262.0,0.0,1.0,1976.0,2.0,460.0
2,68.0,162.0,486.0,0.0,434.0,920.0,1.0,0.0,2001.0,2.0,608.0
3,60.0,0.0,216.0,0.0,540.0,756.0,1.0,0.0,1998.0,3.0,642.0
4,84.0,350.0,655.0,0.0,490.0,1145.0,1.0,0.0,2000.0,3.0,836.0
...,...,...,...,...,...,...,...,...,...,...,...
2914,21.0,0.0,0.0,0.0,546.0,546.0,0.0,0.0,NaN,0.0,0.0
2915,21.0,0.0,252.0,0.0,294.0,546.0,0.0,0.0,1970.0,1.0,286.0
2916,160.0,0.0,1224.0,0.0,0.0,1224.0,1.0,0.0,1960.0,2.0,576.0
2917,62.0,0.0,337.0,0.0,575.0,912.0,0.0,1.0,NaN,0.0,0.0
2918,74.0,94.0,758.0,0.0,238.0,996.0,0.0,0.0,1993.0,3.0,650.0